### ISSUE TITLE
Fix up citations

### ISSUE THREAD

**Issue by petebachant** [petebachant/CFT-Re-dep-paper#53]
## TODO:
- [x] Re does not need to be an equation. Cite some decent fluids text or something.
- [ ] Use citations provided later.
- [x] 39--42 Maybe use Paraschivoiu for this reference.
- [x] 59--65 Include statement from above response. Add something to Tescione citation explaining how they were within reach of the Re-independent state, but it was not confirmed whether this was truly achieved.
- [x] 59--65 Move "high solidity" before "vertical-axis" and move "at optimal tip speed ratio" before "wind tunnel" then cut off everything after the comma.
- [x] 59--65 Make a statement(s) comparing and contrasting the three studies a bit better
- [x] 66--67 Krogstad and Adaramola is 12 percent...
- [x] 73--80 Discuss how there are many studies and we only have selected ones
- [x] Explain how blade chord Re doesn't apply to porous discs, but far wake things should scale with Re_D.
