### ISSUE TITLE
Add exp setup details

### ISSUE THREAD

**Issue by petebachant** [petebachant/CFT-Re-dep-paper#55]
## TODO
- [x] Add side view? This would be quite a project. Maybe add a photo.
- [x] Add tow tank dimensions.
- [x] Measurement volume size of the Vectrino
- [x] Give brands and model numbers of instrumentation.
