### ISSUE TITLE
Qualify what high solidity means

### ISSUE THREAD

**Issue by petebachant** [petebachant/CFT-Re-dep-paper#63]
## TODO
- [x] Revise definition on line 46 (\pi D) in parentheses.
- [x] Define with the c/R also and explain how this creates the flow curvature problem.
- [x] Citation for lambda decreasing with solidity (Templin).
- [x] What is high and low solidity? Fiedler and Tullis say 0.1 threshold, but we could use Migliore and define some delta alpha threshold
