### ISSUE TITLE
Scientific notation on axis labels

### ISSUE THREAD

**Issue by petebachant** [petebachant/CFT-Re-dep-paper#75]
This is hard to do (see #72), but I will have to find a workaround.
## TODO
- [x] `perf_re_dep`
- [x] `all_foils_re_dep`
- [x] `cft_re_dep_foils`
- [x] `wake_trans_totals`
## Strategies
1. Divide both arrays of x-values by `1e6` or `1e5`, then manually place the LaTeX `\times 10^6`.
2. Use standard matplotlib math text for lower axis, and somehow replicate for upper (which will require dividing by `1e5`, which I think is done now. This is a good option since it won't require any extra work on the lower x-axes.
